# Generated by Django 4.1 on 2022-09-18 11:56

import Videos.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Channels', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=64)),
                ('description', models.TextField(default='n/n', max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 56, 56, 361448, tzinfo=datetime.timezone.utc), verbose_name='publication date')),
                ('video_path', models.FileField(upload_to=Videos.models.videos_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('preview_path', models.ImageField(default='previews/base_preview.jpg', upload_to=Videos.models.previews_upload_path)),
                ('views', models.BigIntegerField(default=0)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(null=True, to='Videos.videotags')),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_author', to='Channels.channels')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacted_video', to='Videos.videos')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='Channels.channels')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_video', to='Videos.videos')),
            ],
        ),
    ]
