# Generated by Django 4.1.5 on 2023-01-21 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_rename_date_comments_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 21, 58, 31, 349533, tzinfo=datetime.timezone.utc), verbose_name='publication date'),
        ),
    ]
