# Generated by Django 4.1 on 2022-09-18 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(default=None, max_length=300, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 57, 1, 787419, tzinfo=datetime.timezone.utc), verbose_name='creation date')),
                ('tags', models.ManyToManyField(null=True, to='Channels.channeltags')),
            ],
        ),
    ]
